#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page

sudo apt-get update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

replacement_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"

sudo sed -i "s/server_name _;/$replacement_string/" /etc/nginx/sites-available/default

# creating a 404 error page

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

replacement_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/var\/www\/html;\n\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$replacement_string/" /etc/nginx/sites-available/default

sudo service nginx restart