#!/usr/bin/env bash

sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  yonas-frontend
        bind *:80
        mode http
        default_backend yonas-backend
backend yonas-backend
        balance roundrobin
        server 63210-web-01 100.25.19.204:80 check
        server 63210-web-02 54.157.159.85:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
