#!/usr/bin/env bash
# Configuring an Nginx server (debugging nginx port 80)

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart 